/**
 * Auto-generated by `openapi-typescript` from `openapi/openapi.yaml`.
 * Do not edit by hand.
 *
 * Regenerate with: `pnpm run api:generate`.
 *
 * The current OpenAPI document is intentionally minimal, so this file ships
 * empty type aliases as a temporary placeholder. It will be overwritten the
 * moment real operations land in the schema.
 */
// biome-ignore lint/complexity/noBannedTypes: placeholder until real schema is generated
export type paths = {};
// biome-ignore lint/complexity/noBannedTypes: placeholder until real schema is generated
export type components = {};
// biome-ignore lint/complexity/noBannedTypes: placeholder until real schema is generated
export type operations = {};
